sudo: required
dist: trusty
language: cpp
branches:
  only:
    - master
compiler:
- clang
- gcc
os:
- linux
- osx
env:
  global:
  - secure: OvSuITCwilgERG6G0yvyHMUsjukpZFAfopnazFCmOKh54sS7TnDB2yB0pEMbbPH1UG3WCap2bGGySBvDErq633Ix7E1ZkisuLE3QiUo49zh+388giOc7oOdA6pqNJ75PYjnjHyz5zOxTodZq7rgkF4uLzYCSO7ek63WXMol1Rss1lI9DEOKHw4pFx/PCTRwGIoGWt3t8xP6LUji/sHUWTs9VULVYeTziJCb2LZMsDeo4YZoVzcaZ4WufFdZg3bklzW7flNU5rIVKki6jkWd+72A7QgNjkHpYzljFgBrCSZ7dhMjT1MFnCCA1tFIvTpAT9qlANqmlv9tprRltgtKkoNYq5hac6rbRHQLESk5MMYgwLclHISLut1Fp/QpMmmGArFlwu3Xhp9LoFSaD37n/olq955mQhXQYmWnN+NUfvL9OvOlyT3+E6avqOgPI54WYj9/B1bYbm/Zi9mhGcEAG5/AFtmY546vmhn09d50gPszYzb4MzBIEf2Dggc/NrTE1ZFBCqv9+xch5apJLOjrWJ8Ej75IJwes66MskvOUL/40u8FeWzYaJaq+lRtfR2uBSolko0s2OrmIDJ7BCUgJN8Xsb/joRUcBj9+JBjR4yVy6mSFrgXH/Pz+k8qqSdrufsQjZNJDdEPjoVdb2caY/IIXHiERFYBJGq5vSnp8x7mao=
  - secure: En8/2jtdVEaHp2+S/NMGvfpWSDqY5NT/nE/VMlEuYDAv/blDvyU4R3ZDMufVrUxktd+oX+5TawqZcNFwKC7p3qsZas7S2IoK1bNSrrQhy9xmjGeleMX/SX0jJXv1zAFMi/I5cR38s95mjiyt1hWULMyyLLJjNEpX9ZmOOb7MMo2oPstzRJ1eN4D5G+qbSytYpM8xd/dfWbUufSUUjt3j/HK5JrJpNe3CBE3MlEyDbDeSeDnDjIzz5xaKKba6omfRzQvsgFVpNoJLl6D3or01S0ZgbsiHghdT1kSOvJHeC9FTqgeoZi1GPs2lFZ4HoDDNnrUkYMDzu+h42RrxlGizT3bcI/LvNJk+9AJmJRfeUAWQnEBNZuaucwr1cj67oX55D3gtaFIPMlQ4ZXjuV9Kws/IGKCR16T+h7mtESbyaF9WibGYMVHZAgI/50PZt3z3DVecGjZa96sYCNACTtRaC8qXp/WDxbAQG7uR5zbeqRKsZ9hX/5R2voJgwEn3XCwcEdhKZxv0Ap7dBTlQUiYKX0QpPQXxB5ZMfCwBQx45s8VfZtmSXf4dzy2AgYbBjyX0ieCBA7NxmW0T35HFn7Fyw0PMQwj3tX2ypah9mF/fWpXCIgfmR2jlcUyJXPoEDCAeFdkSZ5XfJAiIK6UCTTSvFutGrOJiUWVkyghhgmvOch0o=
  - secure: gCmUz1yui692ArArhY8H3eFtuIH6CajEjZ5fiHNThdcrRfPpBcz8n72B4VfLWGidYNkOvofHO+NeJnqVIniTUR/sIM5ZoYxY2lV1ExJQHqYvpm5RO8ccOC4NaUvjra8L7O2wLeumOIrs8rgXLeDFUKn9qucn4d4F8ry21El5+/j/q4BSVomouV3PdSdzlg3SaCB0V1dpTp4QUw8Zp2b6F6brNQQ6Ss90ZHWjnyKnAG3nnaIPyStI0HEFgd5sibMpRjv52n0lXrDvsCVvk+jttfbZ8E5ghaDg0I8fWpF7fDk+RrTtDKTVpgKtQTaCQxL5Metv9kguCLAIZUhb4zi4l8A7CBYaBSiBatfPWOLzdvFRwdoeFLXwPeHuJUbKnQDRGATHryqEwe5LiDPAad1CDvHPMRljsVxcgnb5DTNegmHA6TL007T7myCy3ft51OuFF0Zr7UqA4fl96DMbn7G/OOjWpN3R6xFb6fvh/5ERAaM63amyTCR1o1L040wTQ1rbzGrm7E1euKjOeEjD9JGKIym/jrJKCyB25Q89Kef71ms+gYbpZahAncYn9ltyPepINt3nq8woPh4nBmujEJrNDP4aVdMiCKwjAc526G8o0istXOvDfTaC5LropMn/r6m7ZupEYwZLQ81kOZng24u4ZyJPLUA4huOs4WbyW9n2rhA=
  matrix:
  - BUILD_MODE=release
#  - BUILD_MODE=debug
before_install:
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get -y update -qq && sudo apt-get
  -y install qt5-default p7zip-full; fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew update; fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew install qt5; fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then export PATH=$(brew --prefix)/opt/qt5/bin:$PATH;
  fi
install:
- if [ "${TRAVIS_OS_NAME}" = "linux" -a "${CXX}" = "clang++" ]; then exit;
  fi
- if [ "${TRAVIS_OS_NAME}" = "linux" -a "${CXX}" = "g++" ]; then export MKSPEC=linux-g++;
  fi
- if [ "${TRAVIS_OS_NAME}" = "osx" -a "${CXX}" = "clang++" ]; then export MKSPEC=macx-clang;
  fi
- if [ "${TRAVIS_OS_NAME}" = "osx" -a "${CXX}" = "g++" ]; then exit; fi
script:
- git clone https://github.com/LER0ever/Israfil.git
- cd Israfil
- git submodule update --init --recursive
- echo "Building for ${MKSPEC} in ${BUILD_MODE} mode..."
- mkdir build
- cd build
- qmake ../Israfil.pro -spec ${MKSPEC} CONFIG+=${BUILD_MODE}
- make
- ls -lRa .
- mv bin Israfil
- if [ "${BUILD_MODE}" = release -a "${TRAVIS_OS_NAME}" = "osx" ]; then zip -r Israfil.zip
  Israfil && mv Israfil.zip ../../; fi
- if [ "${BUILD_MODE}" = release -a "${TRAVIS_OS_NAME}" = "linux" ]; then 7z a Israfil.zip
  Israfil && mv Israfil.zip ../../; fi
- cd ../../
before_deploy:
- export VERSION_NUMBER=`cat VERSION`
- TIME_STRING=`date +%H%M%S`
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- mv Israfil.zip Israfil-$MKSPEC-$VERSION_NUMBER.zip
- export GIT_TAG=$MKSPEC-$VERSION_NUMBER-$TIME_STRING
#- export GIT_TAG=$VERSION_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://LER0ever:$GITHUB_API_KEY@github.com/LER0ever/Israfil-builds --tags
deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file: Israfil-$MKSPEC-$VERSION_NUMBER.zip
  skip_cleanup: true
  on:
    branch: master
    tags: false
    condition: $BUILD_MODE=release
